@startuml

title "GameEnginePluginConcept"

frame "Host Application" as HA {
[Host Application Interop] as HAI
[Game Engine Plugin] as GEP
() "IGameEnginePlugin" as IGEP
}

IGEP -- GEP

HAI <..> IGEP


@enduml