@startuml

title "XPlaneWrapper"

interface "IGameEnginePlugin"  as IGEP {
}

class "XPLMDisplayApi" as XDA {
  RegisterDrawCallbackFunc
  DrawCallback
  GetScreenSizeFunc
}

class "XPLMGraphicsApi" as XGA {
  SetGraphicsStateFunc
}

class "XPLMProcessingApi" as XPA {
  RegisterFlightLoopCallbackFunc
  FlightLoopCallback
}

class "XPLMCameraApi" as XCA {
  ReadCameraPositionFunc
}

class "XPlaneWrapperFreeFunctions"  as XPW {
    + {static} <<extern C>> int XPluginStart(char *, char *, char *)
    + {static} <<extern C>> SetXplmApiHooks(XPLMDisplayApi, XPLMGraphicsApi, XPLMProcessingApi)
    + {static} <<extern C>> SetGepApiHooks(GepApi)

}

XPW o-- IGEP

XPW -- XDA
XPW -- XGA
XPW -- XPA
XPW -- XCA


@enduml