@startuml

title "XPlaneWrapper"

interface "IGameEnginePlugin"  as IGEP {
    + {static} int GEP Initialize()
}

class "XPLMDisplayApi" as XDA {
  RegisterDrawCallbackFunc
  GetScreenSizeFunc
}

class "XPLMGraphicsApi" as XGA {
  SetGraphicsStateFunc
}

class "XPLMProcessingApi" as XPA {
  RegisterFlightLoopCallbackFunc
}

class "XPlaneWrapperFreeFunctions"  as XPW {
    + {static} <<extern C>> int XPluginStart(char *, char *, char *)
    + {static} <<extern C>> SetXplmApiHooks(XPLMDisplayApi, XPLMGraphicsApi, XPLMProcessingApi)
}

XPW o-- IGEP

XPW -- XDA
XPW -- XGA
XPW -- XPA


@enduml